services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hari_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
